#!/usr/um/bin/perl -w
#
#
use IPC::Open2;


open(DATA,"<$ARGV[0]") 
    || die "Unable to open $ARGV[0] for read: $!";
if (scalar(@ARGV) == 2)
{
  open(OUTPUT,">$ARGV[1]") || die "Unable to open $ARGV[1] for write: $!";
}
else
{
  open(OUTPUT,">-") || die "Unable to open standard out for write: $!";
}

$_ = <DATA>;
print OUTPUT $_;

while (! m/^Restriction:/)
{
  $_ = <DATA>;
  print OUTPUT $_;
}

while (<DATA>)
{
  if (/^Stiffness/)
  {
    print OUTPUT $_;
    for ($i = 1; $i <= 6; $i = $i + 1)
    {
      $rw[$i] = <DATA>;
      print OUTPUT $rw[$i];
    }

    # Read blank line
    $_ = <DATA>;
    print OUTPUT $_;
   
    # Check for Bifurcation info
    $_ = <DATA>;
    print OUTPUT $_;
    if (/^Bifurcation/)
    {
      $pid = open2(PIPout,PIPin,"Rank1Convex 5");

      for ($i = 1; $i <= 6; $i = $i +1)
      {
	print PIPin $rw[$i];
      }
      $_ = <PIPout>;
      close(PIPin);
      close(PIPout);
      waitpid($pid,0);
      print OUTPUT $_;
      print $_;
    }
  }
  else
  {
    print OUTPUT $_;
  }
}

close(OUTPUT);
close(DATA);

