GPLSCRIPTS = AddRank1Convex\
	     BlochWaveRecalc\
	     CoarsenGPL\
	     CoarsenOutput\
	     MultiChain2gpl\
	     MultiLattice2gpl\
	     TwoBarTruss2gpl\
	     FourBarTruss2gpl\
	     QC2gpl\
	     DFT2gpl
