SOLUTIONMETHODS  = KnownSolutionMethods.cpp\
	           RefineEqbmSolution.cpp\
	           ScanningSolution.cpp\
	           ArcLengthSolution.cpp\
	           NewtonPCSolution.cpp\
	           NEBSolution.cpp\
		   ODSolution.cpp
