SOLUTIONMETHODS  = KnownSolutionMethods.cpp\
	           ScanningSolution.cpp\
	           ArcLengthSolution.cpp\
	           NewtonPCSolution.cpp\
	           NewtonUpdatePCSolution.cpp\
	  	   NewtonQRUpdatePCSolution.cpp
