MODES = KnownModes.cpp\
	UniDefTemp2DExpand.cpp\
        UniDefTemp3DExpand.cpp\
	UniDefTemp3DNaCl.cpp\
	UniDefTemp3DRhombo.cpp\
	UniDefTemp3DOrtho.cpp\
	UniDefTemp3D3PMono.cpp\
	UniDefTemp3D3MMono.cpp