POTENTIALS = KnownPairPotentials.cpp\
	     LJ.cpp\
	     LJConstCutoff.cpp\
	     LJLinearCutoff.cpp\
	     LJQuadraticCutoff.cpp\
	     LJSplineCutoff.cpp\
	     RadiiMorse.cpp\
	     RadiiMorseCutoff.cpp\
	     RadiiMorseCutoff2.cpp\
	     RadiiMorseOriginal.cpp\
	     TempMorse.cpp\
	     GVMorse.cpp\
	     Dobson.cpp

PTNLS := $(filter-out KnownPairPotentials.h, $(patsubst Potentials/%,%,$(wildcard Potentials/*.h)))
