POTENTIALS = KnownPairPotentials.cpp\
	     LJ.cpp\
	     LJCutoff.cpp\
	     RadiiMorse.cpp\
	     RadiiMorse2.cpp\
	     RadiiMorseCutoff.cpp\
	     RadiiMorseCutoff2.cpp\
	     TempMorse.cpp\
	     Dobson.cpp

PTNLS := $(filter-out KnownPairPotentials.h, $(patsubst Potentials/%,%,$(wildcard Potentials/*.h)))
