LATTICES = KnownLattices.cpp\
	   SquarePressTempPairPotLat.cpp\
	   TrianglePressTempPairPotLat.cpp\
	   NiTiPressTempPairPotLat.cpp\
	   NiTiShuffle1TPPLat.cpp\
	   NiTiShuffle2TPPLat.cpp\
	   NiTiShuffle3TPPLat.cpp\
	   NiTiRadii.cpp\
	   NiTi15TPPLat.cpp
