LATTICES = KnownLattices.cpp\
	   Lattice.cpp\
	   MultiLatticeTPP.cpp\
	   MultiChainTPP.cpp\
	   MultiChainTTPP.cpp\
	   TwoBarTruss.cpp\
	   TwoBarTrussExternal.cpp\
	   DFTExternal.cpp\
	   QC.cpp\
	   QC-stub.cpp